
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sf-csi-sc-demo-lun1
provisioner: csi-scaleflash
parameters:
    zkServerList: "192.168.68.224:2181,192.168.68.223:2181,192.168.68.222:2181"
    storID: "stor_001"
    clstID: "k8storage"
    lunName: "demo-lun1"
    fsType: "xfs"
    lunPass: "123456"
    lunReadQos: "0"
    lunWriteQos: "0"
    capacity: "100"
    snapCount: "0"
    encryptData: "0"
reclaimPolicy: Delete
volumeBindingMode: Immediate

