
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sf-csi-sc-demo-lun2
provisioner: csi-scaleflash
parameters:
    zkServerList: "192.168.68.84:2181,192.168.68.85:2181,192.168.68.86:2181"
    storID: "stor_001"
    clstID: "k8storage"
    lunName: "demo-lun2"
    fsType: "xfs"
    lunPass: ""
    lunReadQos: "0"
    lunWriteQos: "50"
    capacity: "100"
    snapCount: "0"
    encryptData: "0"
reclaimPolicy: Delete
volumeBindingMode: Immediate

