
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: csi-node-scaleflashplugin
  namespace: k8storage

spec:
  selector:
    matchLabels:
      app: csi-node-scaleflashplugin

  template:
    metadata:
      labels:
        app: csi-node-scaleflashplugin
    spec:
      serviceAccount: csi-service-account
#      hostNetwork: true
      containers:
      - name: driver-registrar
        image: quay.io/k8scsi/csi-node-driver-registrar:v1.3.0
        imagePullPolicy: IfNotPresent
        args:
        - --v=5
        - --csi-address=/csi/csi.sock
        - --kubelet-registration-path=/var/lib/kubelet/plugins/csi-scaleflash/csi.sock
        env:
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /csi
          name: socket-dir
        - mountPath: /registration
          name: registration-dir
        - mountPath: /csi-data-dir
          name: csi-data-dir         

      - name: scaleflash-driver
        image: docker-bj.k8storage.io:33330/scaleflash/k8storage:v1.18-3.4-2
        imagePullPolicy: IfNotPresent
        args:
        - --drivername=csi-scaleflash
        - --v=5
        - --endpoint=$(CSI_ENDPOINT)
        - --nodeid=$(KUBE_NODE_NAME)
        env:
        - name: CSI_ENDPOINT
          value: unix:///csi/csi.sock
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /dev
          name: dev-dir
        - mountPath: /csi
          name: socket-dir
        - mountPath: /csi-data-dir
          name: csi-data-dir
        - mountPath: /var/lib/kubelet/pods
          mountPropagation: Bidirectional
          name: mountpoint-dir
        - mountPath: /var/lib/kubelet/plugins
          mountPropagation: Bidirectional
          name: plugins-dir
        - mountPath: /opt/scaleflash/conf/.scaleflash.lic
          name: scalelfash-conf
          subPath: .scaleflash.lic
        - mountPath: /usr/bin/storadm
          name: storadm-exec
          subPath: storadm

      volumes:
      - hostPath:
          path: /dev
          type: Directory
        name: dev-dir
      - hostPath:
          path: /var/lib/kubelet/plugins/csi-scaleflash
          type: DirectoryOrCreate
        name: socket-dir
      - hostPath:
          path: /var/lib/kubelet/pods
          type: DirectoryOrCreate
        name: mountpoint-dir
      - hostPath:
          path: /var/lib/csi-scaleflash-data/
          type: DirectoryOrCreate
        name: csi-data-dir
      - hostPath:
          path: /var/lib/kubelet/plugins_registry
          type: Directory
        name: registration-dir
      - hostPath:
          path: /var/lib/kubelet/plugins
          type: Directory
        name: plugins-dir
      - name: scalelfash-conf
        hostPath:
          path: /opt/scaleflash/conf/
      - name: storadm-exec
        hostPath:
          path: /opt/scaleflash/bin/

